### ISSUE TITLE
Update satellite logo

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-press-assets#6]
The satellite logo in this repo is outdated. @tatsvc do you have the cleaned up version?

**Comment by tatsvc** [comment]
It's in my Dropbox! Mapbox-design > Tatiana > something with satellite rainbow. Should have all the different file types!

**Comment by samanpwbb** [comment]
@tatsvc can you add this logo to this repo?

**Comment by samanpwbb** [comment]
![](https://media.giphy.com/media/4pMX5rJ4PYAEM/giphy.gif)
