### ISSUE TITLE
update for new Mapbox logo

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-press-assets#8]
the logos folder still contains the old mapbox logo rather than the new one at https://www.mapbox.com/about/press/images/mapbox-logos.zip

/cc @mgosline @samanpwbb

**Comment by mgosline** [comment]
@andrewharvey everything is now in the design repo:
https://github.com/mapbox/design/tree/master/brand/logo

We'd rather not have the same assets living in multiple repos. Would you mind if we closed this repo and directed everyone to Design?

/cc @emilyville

**Comment by andrewharvey** [comment]
@mgosline that repo is private. This one is public.

**Comment by emilyville** [comment]
@andrewharvey Can we direct them to the same download we use on the website? Or does this have a different use case it needs to support...

https://www.mapbox.com/about/press/images/mapbox-logos.zip

**Comment by andrewharvey** [comment]
@emilyville It doesn't really matter to me, it's up to you guys. Having it on github makes it easier to subscribe to changes, but it's not a big deal.
